name: made-collections

on:
  create:
    branches:
      - release/**
  push:
    branches:
    - main
    paths:
    - MADE.Collections/**
    - build/**
    - .github/workflows/made-collections.yml
  pull_request:
    branches:
    - main
    paths:
    - MADE.Collections/**
    - build/**
    - .github/workflows/made-collections.yml
  workflow_dispatch:

defaults:
  run:
    working-directory: MADE.Collections

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get source
        uses: actions/checkout@v2

      - name: Get Build Version
        run: |
          Import-Module .\build\GetBuildVersion.psm1
          Write-Host $Env:GITHUB_REF
          $version = GetBuildVersion -VersionString $Env:GITHUB_REF
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh
      
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Restore dependencies
        run: npm install

      - name: Update Version
        run: npm version $env:BUILD_VERSION

      - name: Build
        run: npm run build

      - name: Publish
        if: startsWith(github.ref, 'refs/heads/release')
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
