name: made-diagnostics

on:
  create:
    branches:
      - release/**
  push:
    branches:
    - main
    paths:
    - MADE.Diagnostics/**
    - build/**
    - .github/workflows/made-diagnostics.yml
  pull_request:
    branches:
    - main
    paths:
    - MADE.Diagnostics/**
    - build/**
    - .github/workflows/made-diagnostics.yml
  workflow_dispatch:

defaults:
  run:
    working-directory: MADE.Diagnostics

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get source
        uses: actions/checkout@v2

      - name: Get Build Version
        run: |
          Import-Module ..\build\GetBuildVersion.psm1
          $version = GetBuildVersion -VersionString $Env:GITHUB_REF
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          Write-Host $version
        shell: pwsh
      
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Restore dependencies
        run: npm install

      - name: Update Version
        run: npm version $BUILD_VERSION

      - name: Build
        run: npm run build

      - name: Publish
        if: startsWith(github.ref, 'refs/heads/release')
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
